### ISSUE TITLE
Limit features in one tile

### ISSUE THREAD

**Issue by StefanBrand** [submarcos/django-vectortiles#11]
I tried to slice the input `QuerySet` like this: `self.queryset = input_queryset[:10000]` to limit features per tile. I got this error:

```
Fail: AssertionError: Cannot filter a query once a slice has been taken.
```

Thinking about it, it does not make sense to slice before the spatial intersection, of course. So this would have to be done after this line:

https://github.com/submarcos/django-vectortiles/blob/fb2ad8ca8ea9c4384a5325599c95f363ce9e89f9/vectortiles/postgis/mixins.py#L20

FYI: [`pg_tileserv`](https://github.com/CrunchyData/pg_tileserv) has a [default features per tile of 10000](https://github.com/CrunchyData/pg_tileserv#configuration-file).

**Comment by submarcos** [comment]
ok, maybe by adding vector_tile_feature_limit = None and passing it to get_tile
