### ISSUE TITLE
Django Rest Framework Compatability - Not Accepted 406

### ISSUE THREAD

**Issue by StefanBrand** [submarcos/django-vectortiles#26]
I was trying to use a DRF view with django-vectortiles, as mentioned in the [README](https://github.com/submarcos/django-vectortiles#usage-with-drf). When I do a tileserver view like this:

```py
class TileServerView(MVTView, views.APIView):
    def get(self, request: Request, *args, **kwargs) -> HttpResponse:
        return BaseVectorTileView.get(
            self,
            request=request,
            z=kwargs.get("z"),
            x=kwargs.get("x"),
            y=kwargs.get("y"),
        )
```

I get `<Response status_code=406, "application/json">` ("Could not satisfy the request Accept header"). This is probably due to DRF's [content negotiation](https://www.django-rest-framework.org/api-guide/content-negotiation/).

As a workaround I provide a custom renderer:

```py
class MVTRenderer(renderers.BaseRenderer):
    media_type = "application/vnd.mapbox-vector-tile"
    format = "pbf"

    def render(self, data, accepted_media_type=None, renderer_context=None):
        return data


class TileServerView(MVTView, views.APIView):
    renderer_classes = [MVTRenderer]
    ...
```

@submarcos If helpful, I can add some hint to the README. I'm even wondering if `MVTView` shouldn't add `renderer_classes` by default...

**Comment by submarcos** [comment]
Hi, thank you @StefanBrand . Yes could propose that in README, even add a MVTRenderer mixin if you want

**Comment by StefanBrand** [comment]
Hi, @submarcos . I went for a simple addition to the README because I did not want to introduce a dependency on DRF.

I'm happy to make any changes to the PR if you have suggestions. :)
