### ISSUE TITLE
Multiple table model in MVTView

### ISSUE THREAD

**Issue by jeyasurya520** [submarcos/django-vectortiles#44]
Is it possible to have multiple table in MVTView model , i'm able to do with a single table but my requirement is to have more than one table in one MVTView model

**Comment by StefanBrand** [comment]
Please share some more information. It is difficult to imagine what you are trying to accomplish.

1. Are you trying to combine multiple querysets?
2. How do your models look like?
3. How does your current implementation look like?
4. What does not work with your current implementation?

**Comment by jeyasurya520** [comment]
Yes ,i'm trying to combine multiple querysets 

Below this how my view class look like,hear i trying to add multiple models(tables)
class RunwayMVT(MVTView, APIView):
    vector_tile_queryset = Runway.objects.all()
    vector_tile_layer_name = "runway"
    vector_tile_fields = ('runway_id',)
    vector_tile_geom_name = "geometry"
    renderer_classes = (MVTRenderer,)
    vector_tile_content_type = "application/x-protobuf"

I have more than 200  different table for different layers , so now i need to create a single View where all data from all table should be fetched and serve as vectortiles.

**Comment by StefanBrand** [comment]
Union should work to combine querysets: https://docs.djangoproject.com/en/4.2/ref/models/querysets/#union

```python
vector_tile_queryset = Layer1.objects.all().union(Layer2.objects.all(), Layer3.objects.all())
```

For the fields, you must be attentive to the documentation of `Queryset.union`: The first queryset defines the available field names.

**Comment by submarcos** [comment]
Hi @jeyasurya520

Take a look to v1 branch and [v1 beta pypi release](https://pypi.org/project/django-vectortiles/1.0.0b3/)

Multiple layers (and models) per tile is now possible

I am working on test to release 1.0 next

**Comment by jeyasurya520** [comment]
Hi @submarcos  In  MVTView   api call ,why the coordinates values are changing in feature .

**Comment by submarcos** [comment]
https://epsg.io/3857

Your point is out of EPSG 3857 bounds

**Comment by StefanBrand** [comment]
Indeed, Web Mercator is not defined in the pole regions. In theory, it should be possible to transform geometry and envelope to a polar CRS like [WGS 84 / Antarctic Polar Stereographic - EPSG:3031](https://epsg.io/3031). Currently, we hardcode `3857`:

https://github.com/submarcos/django-vectortiles/blob/a21e571d0165e46a4cea1a81d7dec1ae08c7ce7b/vectortiles/postgis/mixins.py#L23-L31

PS.: I think this should be a new issue.

**Comment by kannan-ts** [comment]
@submarcos Is Multiple layers (and models) per tile functionality available in master?

**Comment by 950083** [comment]
> Can you suggest me with the solution for run  it as asyncronous call

**Comment by submarcos** [comment]
> @submarcos Is Multiple layers (and models) per tile functionality available in master?

For now, yes it is.

I'm going to fix CI, tests and release in next days

**Comment by submarcos** [comment]
From v1, it's now possible to handle multiple tables in a signle MVTView
